from typing import Final

COLOUR_SETS: Final = {
    0: {
        "colourName": "Grass",
        "mapdatId": 1,
        "tonesRGB": {
            "dark": (89, 125, 39),
            "normal": (109, 153, 48),
            "light": (127, 178, 56),
            "unobtainable": (67, 94, 29),
        },
        "blocks": [
            {"name": "grass_block", "support": False, "flammable": False},
            {"name": "slime_block", "support": True, "flammable": False},
        ],
    },
    1: {
        "colourName": "Sand",
        "mapdatId": 2,
        "tonesRGB": {
            "dark": (174, 164, 115),
            "normal": (213, 201, 140),
            "light": (247, 233, 163),
            "unobtainable": (130, 123, 86),
        },
        "blocks": [
            {"name": "sand", "support": True, "flammable": False},
            {"name": "sandstone", "support": False, "flammable": False},
            {"name": "sandstone_slab", "support": True, "flammable": False},
            {"name": "birch_log", "support": False, "flammable": True},
            {"name": "birch_planks", "support": False, "flammable": True},
            {"name": "birch_slab", "support": True, "flammable": True},
            {"name": "glowstone", "support": False, "flammable": False},
            {"name": "end_stone", "support": False, "flammable": False},
            {"name": "end_stone_bricks", "support": False, "flammable": False},
            {"name": "end_stone_brick_slab", "support": True, "flammable": False},
            {"name": "bone_block", "support": False, "flammable": False},
            {"name": "birch_pressure_plate", "support": True, "flammable": False},
            {"name": "ochre_froglight", "support": False, "flammable": False},
        ],
    },
    2: {
        "colourName": "Cobweb",
        "mapdatId": 3,
        "tonesRGB": {
            "dark": (140, 140, 140),
            "normal": (171, 171, 171),
            "light": (199, 199, 199),
            "unobtainable": (105, 105, 105),
        },
        "blocks": [
            {"name": "mushroom_stem", "support": False, "flammable": False},
            {"name": "light_gray_wool", "support": False, "flammable": True},
        ],
    },
    3: {
        "colourName": "TNT",
        "mapdatId": 4,
        "tonesRGB": {
            "dark": (180, 0, 0),
            "normal": (220, 0, 0),
            "light": (255, 0, 0),
            "unobtainable": (135, 0, 0),
        },
        "blocks": [
            {"name": "tnt", "support": False, "flammable": True},
            {"name": "redstone_block", "support": False, "flammable": False},
        ],
    },
    4: {
        "colourName": "Ice",
        "mapdatId": 5,
        "tonesRGB": {
            "dark": (112, 112, 180),
            "normal": (138, 138, 220),
            "light": (160, 160, 255),
            "unobtainable": (84, 84, 135),
        },
        "blocks": [
            {"name": "ice", "support": False, "flammable": False},
            {"name": "packed_ice", "support": False, "flammable": False},
            {"name": "blue_ice", "support": False, "flammable": False},
        ],
    },
    5: {
        "colourName": "Iron",
        "mapdatId": 6,
        "tonesRGB": {
            "dark": (117, 117, 117),
            "normal": (144, 144, 144),
            "light": (167, 167, 167),
            "unobtainable": (88, 88, 88),
        },
        "blocks": [
            {"name": "iron_block", "support": False, "flammable": False},
            {"name": "iron_trapdoor", "support": True, "flammable": False},
            {"name": "heavy_weighted_pressure_plate", "support": True, "flammable": False},
            {"name": "brewing_stand", "support": True, "flammable": False},
        ],
    },
    6: {
        "colourName": "Leaves",
        "mapdatId": 7,
        "tonesRGB": {
            "dark": (0, 87, 0),
            "normal": (0, 106, 0),
            "light": (0, 124, 0),
            "unobtainable": (0, 65, 0),
        },
        "blocks": [
            {"name": "oak_leaves", "support": False, "flammable": True},
            {"name": "spruce_leaves", "support": False, "flammable": True},
            {"name": "birch_leaves", "support": False, "flammable": True},
            {"name": "jungle_leaves", "support": False, "flammable": True},
            {"name": "acacia_leaves", "support": False, "flammable": True},
            {"name": "dark_oak_leaves", "support": False, "flammable": True},
            {"name": "azalea_leaves", "support": False, "flammable": True},
        ],
    },
    7: {
        "colourName": "Clay",
        "mapdatId": 9,
        "tonesRGB": {
            "dark": (115, 118, 129),
            "normal": (141, 144, 158),
            "light": (164, 168, 184),
            "unobtainable": (86, 88, 97),
        },
        "blocks": [
            {"name": "clay", "support": False, "flammable": False},
        ],
    },
    8: {
        "colourName": "Dirt",
        "mapdatId": 10,
        "tonesRGB": {
            "dark": (106, 76, 54),
            "normal": (130, 94, 66),
            "light": (151, 109, 77),
            "unobtainable": (79, 57, 40),
        },
        "blocks": [
            {"name": "jungle_log", "support": False, "flammable": True},
            {"name": "jungle_planks", "support": False, "flammable": True},
            {"name": "jungle_slab", "support": True, "flammable": True},
            {"name": "dirt", "support": False, "flammable": False},
            {"name": "coarse_dirt", "support": False, "flammable": False},
            {"name": "rooted_dirt", "support": False, "flammable": False},
            {"name": "jukebox", "support": False, "flammable": False},
            {"name": "granite", "support": False, "flammable": False},
            {"name": "granite_slab", "support": True, "flammable": False},
            {"name": "jungle_pressure_plate", "support": True, "flammable": False},
            {"name": "packed_mud", "support": False, "flammable": False},
        ],
    },
    9: {
        "colourName": "Stone",
        "mapdatId": 11,
        "tonesRGB": {
            "dark": (79, 79, 79),
            "normal": (96, 96, 96),
            "light": (112, 112, 112),
            "unobtainable": (59, 59, 59),
        },
        "blocks": [
            {"name": "cobblestone", "support": False, "flammable": False},
            {"name": "cobblestone_slab", "support": True, "flammable": False},
            {"name": "mossy_cobblestone", "support": False, "flammable": False},
            {"name": "stone", "support": False, "flammable": False},
            {"name": "stone_bricks", "support": False, "flammable": False},
            {"name": "stone_brick_slab", "support": True, "flammable": False},
            {"name": "andesite", "support": False, "flammable": False},
            {"name": "andesite_slab", "support": True, "flammable": False},
            {"name": "bedrock", "support": False, "flammable": False},
            {"name": "gravel", "support": True, "flammable": False},
            {"name": "stone_pressure_plate", "support": True, "flammable": False},
        ],
    },
    10: {
        "colourName": "Water",
        "mapdatId": 12,
        "tonesRGB": {
            "dark": (45, 45, 180),
            "normal": (55, 55, 220),
            "light": (64, 64, 255),
            "unobtainable": (33, 33, 135),
        },
        "blocks": [],
    },
    11: {
        "colourName": "Oak",
        "mapdatId": 13,
        "tonesRGB": {
            "dark": (100, 84, 50),
            "normal": (123, 102, 62),
            "light": (143, 119, 72),
            "unobtainable": (75, 63, 38),
        },
        "blocks": [
            {"name": "oak_log", "support": False, "flammable": True},
            {"name": "oak_planks", "support": False, "flammable": True},
            {"name": "oak_slab", "support": True, "flammable": True},
            {"name": "crafting_table", "support": False, "flammable": True},
            {"name": "oak_pressure_plate", "support": True, "flammable": True},
        ],
    },
    12: {
        "colourName": "Birch",
        "mapdatId": 14,
        "tonesRGB": {
            "dark": (180, 177, 172),
            "normal": (220, 217, 211),
            "light": (255, 252, 245),
            "unobtainable": (135, 133, 129),
        },
        "blocks": [
            {"name": "diorite", "support": False, "flammable": False},
            {"name": "diorite_slab", "support": True, "flammable": False},
            {"name": "quartz_block", "support": False, "flammable": False},
            {"name": "quartz_slab", "support": True, "flammable": False},
            {"name": "sea_lantern", "support": False, "flammable": False},
        ],
    },
    13: {
        "colourName": "White Wool",
        "mapdatId": 8,
        "tonesRGB": {
            "dark": (180, 180, 180),
            "normal": (220, 220, 220),
            "light": (255, 255, 255),
            "unobtainable": (135, 135, 135),
        },
        "blocks": [
            {"name": "white_wool", "support": False, "flammable": True},
            {"name": "white_carpet", "support": True, "flammable": True},
            {"name": "white_concrete", "support": False, "flammable": False},
            {"name": "white_concrete_powder", "support": True, "flammable": False},
            {"name": "white_glazed_terracotta", "support": False, "flammable": False},
            {"name": "snow_block", "support": False, "flammable": False},
            {"name": "snow_layer", "support": True, "flammable": False},
        ],
    },
    14: {
        "colourName": "Orange Wool",
        "mapdatId": 15,
        "tonesRGB": {
            "dark": (152, 89, 36),
            "normal": (186, 109, 44),
            "light": (216, 127, 51),
            "unobtainable": (114, 67, 27),
        },
        "blocks": [
            {"name": "orange_wool", "support": False, "flammable": True},
            {"name": "orange_carpet", "support": True, "flammable": True},
            {"name": "orange_concrete", "support": False, "flammable": False},
            {"name": "orange_concrete_powder", "support": True, "flammable": False},
            {"name": "orange_glazed_terracotta", "support": False, "flammable": False},
            {"name": "orange_concrete_powder", "support": True, "flammable": False},
            {"name": "orange_glazed_terracotta", "support": False, "flammable": False},
            {"name": "pumpkin", "support": False, "flammable": True},
            {"name": "acacia_log", "support": False, "flammable": True},
            {"name": "acacia_planks", "support": False, "flammable": True},
            {"name": "acacia_slab", "support": True, "flammable": True},
            {"name": "red_sand", "support": True, "flammable": False},
            {"name": "red_sandstone", "support": False, "flammable": False},
            {"name": "red_sandstone_slab", "support": True, "flammable": False},
            {"name": "terracotta", "support": False, "flammable": False},
            {"name": "honey_block", "support": False, "flammable": False},
            {"name": "honeycomb_block", "support": False, "flammable": False},
            {"name": "raw_copper_block", "support": False, "flammable": False},
            {"name": "waxed_copper_block", "support": False, "flammable": False},
            {"name": "waxed_cut_copper_slab", "support": True, "flammable": False},
        ],
    },
    15: {
        "colourName": "Magenta Wool",
        "mapdatId": 16,
        "tonesRGB": {
            "dark": (125, 53, 152),
            "normal": (153, 65, 186),
            "light": (178, 76, 216),
            "unobtainable": (94, 40, 114),
        },
        "blocks": [
            {"name": "magenta_wool", "support": False, "flammable": True},
            {"name": "magenta_carpet", "support": True, "flammable": True},
            {"name": "magenta_concrete", "support": False, "flammable": False},
            {"name": "magenta_concrete_powder", "support": True, "flammable": False},
            {"name": "magenta_glazed_terracotta", "support": False, "flammable": False},
            {"name": "purpur_block", "support": False, "flammable": False},
            {"name": "purpur_slab", "support": True, "flammable": False},
        ],
    },
    16: {
        "colourName": "Light Blue Wool",
        "mapdatId": 17,
        "tonesRGB": {
            "dark": (72, 108, 152),
            "normal": (88, 132, 186),
            "light": (102, 153, 216),
            "unobtainable": (54, 81, 114),
        },
        "blocks": [
            {"name": "light_blue_wool", "support": False, "flammable": True},
            {"name": "light_blue_carpet", "support": True, "flammable": True},
            {"name": "light_blue_concrete", "support": False, "flammable": False},
            {"name": "light_blue_concrete_powder", "support": True, "flammable": False},
            {"name": "light_blue_glazed_terracotta", "support": False, "flammable": False},
        ],
    },
    17: {
        "colourName": "Yellow Wool",
        "mapdatId": 18,
        "tonesRGB": {
            "dark": (161, 161, 36),
            "normal": (197, 197, 44),
            "light": (229, 229, 51),
            "unobtainable": (121, 121, 27),
        },
        "blocks": [
            {"name": "yellow_wool", "support": False, "flammable": True},
            {"name": "yellow_carpet", "support": True, "flammable": True},
            {"name": "yellow_concrete", "support": False, "flammable": False},
            {"name": "yellow_concrete_powder", "support": True, "flammable": False},
            {"name": "yellow_glazed_terracotta", "support": False, "flammable": False},
            {"name": "hay_block", "support": False, "flammable": True},
            {"name": "sponge", "support": False, "flammable": False},
            {"name": "bamboo_planks", "support": False, "flammable": True},
            {"name": "bamboo_slab", "support": True, "flammable": True},
            {"name": "bamboo_mosaic", "support": False, "flammable": True},
        ],
    },
    18: {
        "colourName": "Lime Wool",
        "mapdatId": 19,
        "tonesRGB": {
            "dark": (89, 144, 17),
            "normal": (109, 176, 21),
            "light": (127, 204, 25),
            "unobtainable": (67, 108, 13),
        },
        "blocks": [
            {"name": "lime_wool", "support": False, "flammable": True},
            {"name": "lime_carpet", "support": True, "flammable": True},
            {"name": "lime_concrete", "support": False, "flammable": False},
            {"name": "lime_concrete_powder", "support": True, "flammable": False},
            {"name": "lime_glazed_terracotta", "support": False, "flammable": False},
            {"name": "melon_block", "support": False, "flammable": True},
        ],
    },
    19: {
        "colourName": "Pink Wool",
        "mapdatId": 20,
        "tonesRGB": {
            "dark": (170, 89, 116),
            "normal": (208, 109, 142),
            "light": (242, 127, 165),
            "unobtainable": (128, 67, 87),
        },
        "blocks": [
            {"name": "pink_wool", "support": False, "flammable": True},
            {"name": "pink_carpet", "support": True, "flammable": True},
            {"name": "pink_concrete", "support": False, "flammable": False},
            {"name": "pink_concrete_powder", "support": True, "flammable": False},
            {"name": "pink_glazed_terracotta", "support": False, "flammable": False},
            {"name": "cherry_log", "support": False, "flammable": True},
            {"name": "cherry_planks", "support": False, "flammable": True},
            {"name": "cherry_slab", "support": True, "flammable": True},
            {"name": "cherry_leaves", "support": False, "flammable": True},
        ],
    },
    20: {
        "colourName": "Grey Wool",
        "mapdatId": 21,
        "tonesRGB": {
            "dark": (65, 65, 65),
            "normal": (79, 79, 79),
            "light": (92, 92, 92),
            "unobtainable": (49, 49, 49),
        },
        "blocks": [
            {"name": "gray_wool", "support": False, "flammable": True},
            {"name": "gray_carpet", "support": True, "flammable": True},
            {"name": "gray_concrete", "support": False, "flammable": False},
            {"name": "gray_concrete_powder", "support": True, "flammable": False},
            {"name": "gray_glazed_terracotta", "support": False, "flammable": False},
        ],
    },
    21: {
        "colourName": "Light Grey Wool",
        "mapdatId": 22,
        "tonesRGB": {
            "dark": (166, 161, 161),
            "normal": (203, 197, 197),
            "light": (236, 229, 229),
            "unobtainable": (125, 121, 121),
        },
        "blocks": [
            {"name": "light_gray_wool", "support": False, "flammable": True},
            {"name": "light_gray_carpet", "support": True, "flammable": True},
            {"name": "light_gray_concrete", "support": False, "flammable": False},
            {"name": "light_gray_concrete_powder", "support": True, "flammable": False},
            {"name": "light_gray_glazed_terracotta", "support": False, "flammable": False},
        ],
    },
    22: {
        "colourName": "Cyan Wool",
        "mapdatId": 23,
        "tonesRGB": {
            "dark": (44, 124, 125),
            "normal": (53, 152, 153),
            "light": (62, 176, 178),
            "unobtainable": (33, 93, 94),
        },
        "blocks": [
            {"name": "cyan_wool", "support": False, "flammable": True},
            {"name": "cyan_carpet", "support": True, "flammable": True},
            {"name": "cyan_concrete", "support": False, "flammable": False},
            {"name": "cyan_concrete_powder", "support": True, "flammable": False},
            {"name": "cyan_glazed_terracotta", "support": False, "flammable": False},
        ],
    },
    23: {
        "colourName": "Purple Wool",
        "mapdatId": 24,
        "tonesRGB": {
            "dark": (107, 57, 132),
            "normal": (131, 70, 161),
            "light": (152, 81, 187),
            "unobtainable": (80, 43, 99),
        },
        "blocks": [
            {"name": "purple_wool", "support": False, "flammable": True},
            {"name": "purple_carpet", "support": True, "flammable": True},
            {"name": "purple_concrete", "support": False, "flammable": False},
            {"name": "purple_concrete_powder", "support": True, "flammable": False},
            {"name": "purple_glazed_terracotta", "support": False, "flammable": False},
        ],
    },
    24: {
        "colourName": "Blue Wool",
        "mapdatId": 25,
        "tonesRGB": {
            "dark": (54, 54, 132),
            "normal": (66, 66, 161),
            "light": (76, 76, 187),
            "unobtainable": (40, 40, 99),
        },
        "blocks": [
            {"name": "blue_wool", "support": False, "flammable": True},
            {"name": "blue_carpet", "support": True, "flammable": True},
            {"name": "blue_concrete", "support": False, "flammable": False},
            {"name": "blue_concrete_powder", "support": True, "flammable": False},
            {"name": "blue_glazed_terracotta", "support": False, "flammable": False},
            {"name": "lapis_block", "support": False, "flammable": False},
        ],
    },
    25: {
        "colourName": "Brown Wool",
        "mapdatId": 26,
        "tonesRGB": {
            "dark": (89, 60, 32),
            "normal": (109, 73, 39),
            "light": (127, 85, 45),
            "unobtainable": (67, 45, 24),
        },
        "blocks": [
            {"name": "brown_wool", "support": False, "flammable": True},
            {"name": "brown_carpet", "support": True, "flammable": True},
            {"name": "brown_concrete", "support": False, "flammable": False},
            {"name": "brown_concrete_powder", "support": True, "flammable": False},
            {"name": "brown_glazed_terracotta", "support": False, "flammable": False},
            {"name": "soul_sand", "support": True, "flammable": False},
            {"name": "soul_soil", "support": False, "flammable": False},
        ],
    },
    26: {
        "colourName": "Green Wool",
        "mapdatId": 27,
        "tonesRGB": {
            "dark": (38, 89, 27),
            "normal": (47, 109, 33),
            "light": (55, 127, 38),
            "unobtainable": (29, 67, 20),
        },
        "blocks": [
            {"name": "green_wool", "support": False, "flammable": True},
            {"name": "green_carpet", "support": True, "flammable": True},
            {"name": "green_concrete", "support": False, "flammable": False},
            {"name": "green_concrete_powder", "support": True, "flammable": False},
            {"name": "green_glazed_terracotta", "support": False, "flammable": False},
        ],
    },
    27: {
        "colourName": "Red Wool",
        "mapdatId": 28,
        "tonesRGB": {
            "dark": (110, 33, 33),
            "normal": (135, 40, 40),
            "light": (157, 47, 47),
            "unobtainable": (82, 25, 25),
        },
        "blocks": [
            {"name": "red_wool", "support": False, "flammable": True},
            {"name": "red_carpet", "support": True, "flammable": True},
            {"name": "red_concrete", "support": False, "flammable": False},
            {"name": "red_concrete_powder", "support": True, "flammable": False},
            {"name": "red_glazed_terracotta", "support": False, "flammable": False},
            {"name": "nether_wart_block", "support": False, "flammable": False},
            {"name": "red_mushroom_block", "support": False, "flammable": False},
        ],
    },
    28: {
        "colourName": "Black Wool",
        "mapdatId": 29,
        "tonesRGB": {
            "dark": (22, 22, 22),
            "normal": (27, 27, 27),
            "light": (31, 31, 31),
            "unobtainable": (16, 16, 16),
        },
        "blocks": [
            {"name": "black_wool", "support": False, "flammable": True},
            {"name": "black_carpet", "support": True, "flammable": True},
            {"name": "black_concrete", "support": False, "flammable": False},
            {"name": "black_concrete_powder", "support": True, "flammable": False},
            {"name": "black_glazed_terracotta", "support": False, "flammable": False},
            {"name": "obsidian", "support": False, "flammable": False},
            {"name": "coal_block", "support": False, "flammable": True},
        ],
    },
    29: {
        "colourName": "Gold",
        "mapdatId": 30,
        "tonesRGB": {
            "dark": (129, 100, 39),
            "normal": (158, 122, 47),
            "light": (184, 142, 55),
            "unobtainable": (97, 75, 29),
        },
        "blocks": [
            {"name": "gold_block", "support": False, "flammable": False},
            {"name": "raw_gold_block", "support": False, "flammable": False},
        ],
    },
    30: {
        "colourName": "Diamond",
        "mapdatId": 31,
        "tonesRGB": {
            "dark": (55, 131, 107),
            "normal": (67, 160, 130),
            "light": (78, 186, 152),
            "unobtainable": (41, 98, 80),
        },
        "blocks": [
            {"name": "diamond_block", "support": False, "flammable": False},
            {"name": "prismarine_bricks", "support": False, "flammable": False},
        ],
    },
    31: {
        "colourName": "Lapis",
        "mapdatId": 32,
        "tonesRGB": {
            "dark": (23, 42, 108),
            "normal": (28, 51, 132),
            "light": (33, 59, 153),
            "unobtainable": (17, 31, 81),
        },
        "blocks": [
            {"name": "warped_wart_block", "support": False, "flammable": False},
        ],
    },
    32: {
        "colourName": "Emerald",
        "mapdatId": 33,
        "tonesRGB": {
            "dark": (46, 106, 52),
            "normal": (56, 130, 64),
            "light": (65, 151, 74),
            "unobtainable": (34, 79, 39),
        },
        "blocks": [
            {"name": "emerald_block", "support": False, "flammable": False},
        ],
    },
    33: {
        "colourName": "Obsidian",
        "mapdatId": 34,
        "tonesRGB": {
            "dark": (63, 44, 44),
            "normal": (77, 54, 54),
            "light": (89, 63, 63),
            "unobtainable": (47, 33, 33),
        },
        "blocks": [
            {"name": "netherrack", "support": False, "flammable": False},
            {"name": "nether_bricks", "support": False, "flammable": False},
            {"name": "nether_brick_slab", "support": True, "flammable": False},
            {"name": "red_nether_bricks", "support": False, "flammable": False},
            {"name": "crimson_nylium", "support": False, "flammable": False},
        ],
    },
    34: {
        "colourName": "Netherrack",
        "mapdatId": 35,
        "tonesRGB": {
            "dark": (97, 26, 26),
            "normal": (119, 32, 32),
            "light": (138, 37, 37),
            "unobtainable": (73, 19, 19),
        },
        "blocks": [
            {"name": "crimson_stem", "support": False, "flammable": True},
            {"name": "crimson_hyphae", "support": False, "flammable": True},
            {"name": "stripped_crimson_stem", "support": False, "flammable": True},
            {"name": "stripped_crimson_hyphae", "support": False, "flammable": True},
        ],
    },
    35: {
        "colourName": "White Terracotta",
        "mapdatId": 36,
        "tonesRGB": {
            "dark": (132, 117, 97),
            "normal": (162, 144, 119),
            "light": (188, 167, 138),
            "unobtainable": (99, 88, 73),
        },
        "blocks": [
            {"name": "white_terracotta", "support": False, "flammable": False},
        ],
    },
    36: {
        "colourName": "Orange Terracotta",
        "mapdatId": 37,
        "tonesRGB": {
            "dark": (93, 59, 24),
            "normal": (114, 72, 29),
            "light": (132, 84, 34),
            "unobtainable": (70, 44, 18),
        },
        "blocks": [
            {"name": "orange_terracotta", "support": False, "flammable": False},
        ],
    },
    37: {
        "colourName": "Magenta Terracotta",
        "mapdatId": 38,
        "tonesRGB": {
            "dark": (95, 60, 67),
            "normal": (116, 74, 82),
            "light": (135, 86, 95),
            "unobtainable": (71, 45, 50),
        },
        "blocks": [
            {"name": "magenta_terracotta", "support": False, "flammable": False},
        ],
    },
    38: {
        "colourName": "Light Blue Terracotta",
        "mapdatId": 39,
        "tonesRGB": {
            "dark": (77, 78, 92),
            "normal": (95, 96, 112),
            "light": (110, 111, 130),
            "unobtainable": (58, 58, 69),
        },
        "blocks": [
            {"name": "light_blue_terracotta", "support": False, "flammable": False},
        ],
    },
    39: {
        "colourName": "Yellow Terracotta",
        "mapdatId": 40,
        "tonesRGB": {
            "dark": (113, 86, 38),
            "normal": (138, 105, 46),
            "light": (160, 122, 54),
            "unobtainable": (85, 64, 28),
        },
        "blocks": [
            {"name": "yellow_terracotta", "support": False, "flammable": False},
        ],
    },
    40: {
        "colourName": "Lime Terracotta",
        "mapdatId": 41,
        "tonesRGB": {
            "dark": (70, 80, 59),
            "normal": (86, 98, 72),
            "light": (100, 114, 84),
            "unobtainable": (52, 60, 44),
        },
        "blocks": [
            {"name": "lime_terracotta", "support": False, "flammable": False},
        ],
    },
    41: {
        "colourName": "Pink Terracotta",
        "mapdatId": 42,
        "tonesRGB": {
            "dark": (95, 58, 57),
            "normal": (116, 71, 70),
            "light": (135, 82, 81),
            "unobtainable": (71, 43, 43),
        },
        "blocks": [
            {"name": "pink_terracotta", "support": False, "flammable": False},
        ],
    },
    42: {
        "colourName": "Grey Terracotta",
        "mapdatId": 43,
        "tonesRGB": {
            "dark": (60, 56, 51),
            "normal": (74, 69, 63),
            "light": (86, 80, 73),
            "unobtainable": (45, 42, 38),
        },
        "blocks": [
            {"name": "gray_terracotta", "support": False, "flammable": False},
        ],
    },
    43: {
        "colourName": "Light Grey Terracotta",
        "mapdatId": 44,
        "tonesRGB": {
            "dark": (79, 62, 57),
            "normal": (97, 76, 70),
            "light": (112, 88, 81),
            "unobtainable": (59, 46, 43),
        },
        "blocks": [
            {"name": "light_gray_terracotta", "support": False, "flammable": False},
        ],
    },
    44: {
        "colourName": "Cyan Terracotta",
        "mapdatId": 45,
        "tonesRGB": {
            "dark": (56, 68, 64),
            "normal": (69, 83, 78),
            "light": (80, 97, 91),
            "unobtainable": (42, 51, 48),
        },
        "blocks": [
            {"name": "cyan_terracotta", "support": False, "flammable": False},
        ],
    },
    45: {
        "colourName": "Purple Terracotta",
        "mapdatId": 46,
        "tonesRGB": {
            "dark": (66, 53, 63),
            "normal": (81, 65, 78),
            "light": (94, 75, 90),
            "unobtainable": (49, 40, 47),
        },
        "blocks": [
            {"name": "purple_terracotta", "support": False, "flammable": False},
        ],
    },
    46: {
        "colourName": "Blue Terracotta",
        "mapdatId": 47,
        "tonesRGB": {
            "dark": (54, 49, 71),
            "normal": (66, 60, 87),
            "light": (76, 70, 101),
            "unobtainable": (40, 37, 53),
        },
        "blocks": [
            {"name": "blue_terracotta", "support": False, "flammable": False},
        ],
    },
    47: {
        "colourName": "Brown Terracotta",
        "mapdatId": 48,
        "tonesRGB": {
            "dark": (66, 44, 27),
            "normal": (81, 54, 33),
            "light": (94, 63, 38),
            "unobtainable": (49, 33, 20),
        },
        "blocks": [
            {"name": "brown_terracotta", "support": False, "flammable": False},
        ],
    },
    48: {
        "colourName": "Green Terracotta",
        "mapdatId": 49,
        "tonesRGB": {
            "dark": (59, 59, 47),
            "normal": (72, 72, 58),
            "light": (84, 84, 67),
            "unobtainable": (44, 44, 35),
        },
        "blocks": [
            {"name": "green_terracotta", "support": False, "flammable": False},
        ],
    },
    49: {
        "colourName": "Red Terracotta",
        "mapdatId": 50,
        "tonesRGB": {
            "dark": (68, 36, 33),
            "normal": (83, 45, 41),
            "light": (97, 52, 47),
            "unobtainable": (51, 27, 25),
        },
        "blocks": [
            {"name": "red_terracotta", "support": False, "flammable": False},
        ],
    },
    50: {
        "colourName": "Black Terracotta",
        "mapdatId": 51,
        "tonesRGB": {
            "dark": (30, 20, 18),
            "normal": (37, 25, 22),
            "light": (43, 29, 26),
            "unobtainable": (22, 15, 13),
        },
        "blocks": [
            {"name": "black_terracotta", "support": False, "flammable": False},
        ],
    },
    51: {
        "colourName": "Crimson Nylium",
        "mapdatId": 52,
        "tonesRGB": {
            "dark": (168, 64, 45),
            "normal": (206, 78, 55),
            "light": (239, 91, 64),
            "unobtainable": (126, 48, 34),
        },
        "blocks": [
            {"name": "shroomlight", "support": False, "flammable": False},
        ],
    },
    52: {
        "colourName": "Crimson Stem",
        "mapdatId": 53,
        "tonesRGB": {
            "dark": (132, 62, 58),
            "normal": (162, 76, 72),
            "light": (188, 88, 83),
            "unobtainable": (99, 46, 43),
        },
        "blocks": [
            {"name": "nether_gold_ore", "support": False, "flammable": False},
        ],
    },
    53: {
        "colourName": "Warped Nylium",
        "mapdatId": 54,
        "tonesRGB": {
            "dark": (46, 107, 107),
            "normal": (56, 131, 131),
            "light": (65, 152, 152),
            "unobtainable": (34, 80, 80),
        },
        "blocks": [
            {"name": "warped_stem", "support": False, "flammable": True},
            {"name": "warped_hyphae", "support": False, "flammable": True},
        ],
    },
    54: {
        "colourName": "Warped Stem",
        "mapdatId": 55,
        "tonesRGB": {
            "dark": (38, 68, 55),
            "normal": (47, 83, 68),
            "light": (54, 97, 79),
            "unobtainable": (28, 51, 42),
        },
        "blocks": [],
    },
    55: {
        "colourName": "Warped Wart Block",
        "mapdatId": 56,
        "tonesRGB": {
            "dark": (106, 138, 26),
            "normal": (130, 169, 32),
            "light": (151, 196, 37),
            "unobtainable": (79, 103, 19),
        },
        "blocks": [
            {"name": "moss_block", "support": False, "flammable": False},
        ],
    },
    56: {
        "colourName": "Deepslate",
        "mapdatId": 57,
        "tonesRGB": {
            "dark": (57, 57, 57),
            "normal": (69, 69, 69),
            "light": (81, 81, 81),
            "unobtainable": (43, 43, 43),
        },
        "blocks": [
            {"name": "deepslate", "support": False, "flammable": False},
            {"name": "cobbled_deepslate", "support": False, "flammable": False},
            {"name": "cobbled_deepslate_slab", "support": True, "flammable": False},
            {"name": "polished_deepslate", "support": False, "flammable": False},
            {"name": "deepslate_bricks", "support": False, "flammable": False},
            {"name": "deepslate_tiles", "support": False, "flammable": False},
            {"name": "reinforced_deepslate", "support": False, "flammable": False},
        ],
    },
    57: {
        "colourName": "Raw Iron",
        "mapdatId": 58,
        "tonesRGB": {
            "dark": (119, 94, 85),
            "normal": (146, 115, 104),
            "light": (170, 134, 121),
            "unobtainable": (89, 70, 64),
        },
        "blocks": [
            {"name": "raw_iron_block", "support": False, "flammable": False},
            {"name": "spruce_planks", "support": False, "flammable": True},
            {"name": "spruce_slab", "support": True, "flammable": True},
            {"name": "spruce_log", "support": False, "flammable": True},
            {"name": "dark_oak_planks", "support": False, "flammable": True},
            {"name": "dark_oak_slab", "support": True, "flammable": True},
            {"name": "stripped_spruce_log", "support": False, "flammable": True},
            {"name": "stripped_dark_oak_log", "support": False, "flammable": True},
        ],
    },
    58: {
        "colourName": "Glow Lichen",
        "mapdatId": 59,
        "tonesRGB": {
            "dark": (97, 97, 97),
            "normal": (119, 119, 119),
            "light": (138, 138, 138),
            "unobtainable": (73, 73, 73),
        },
        "blocks": [
            {"name": "smooth_basalt", "support": False, "flammable": False},
        ],
    },
    59: {
        "colourName": "Mud/Mangrove",
        "mapdatId": 60,
        "tonesRGB": {
            "dark": (64, 43, 33),
            "normal": (79, 52, 40),
            "light": (92, 61, 47),
            "unobtainable": (48, 32, 25),
        },
        "blocks": [
            {"name": "mud", "support": False, "flammable": False},
            {"name": "mud_bricks", "support": False, "flammable": False},
            {"name": "mud_brick_slab", "support": True, "flammable": False},
            {"name": "mangrove_planks", "support": False, "flammable": True},
            {"name": "mangrove_slab", "support": True, "flammable": True},
            {"name": "mangrove_log", "support": False, "flammable": True},
            {"name": "mangrove_roots", "support": False, "flammable": True},
        ],
    },
    60: {
        "colourName": "Cherry",
        "mapdatId": 61,
        "tonesRGB": {
            "dark": (197, 108, 103),
            "normal": (241, 132, 126),
            "light": (255, 154, 147),
            "unobtainable": (148, 81, 77),
        },
        "blocks": [],
    },
    61: {
        "colourName": "Block of Amethyst",
        "mapdatId": 62,
        "tonesRGB": {
            "dark": (115, 65, 158),
            "normal": (141, 79, 193),
            "light": (164, 92, 224),
            "unobtainable": (86, 49, 119),
        },
        "blocks": [
            {"name": "amethyst_block", "support": False, "flammable": False},
            {"name": "budding_amethyst", "support": False, "flammable": False},
        ],
    },
    62: {
        "colourName": "Mangrove Log",
        "mapdatId": 63,
        "tonesRGB": {
            "dark": (75, 66, 41),
            "normal": (92, 81, 50),
            "light": (107, 94, 58),
            "unobtainable": (56, 49, 31),
        },
        "blocks": [],
    },
    63: {
        "colourName": "Suspicious Gravel",
        "mapdatId": 64,
        "tonesRGB": {
            "dark": (158, 103, 68),
            "normal": (193, 126, 83),
            "light": (224, 146, 97),
            "unobtainable": (119, 77, 51),
        },
        "blocks": [
            {"name": "stripped_birch_log", "support": False, "flammable": True},
        ],
    },
}
